apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-3aap
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0044-tenant/tkrw-pr712-0075-0044-app/devfile-sample-3aap@sha256:8f0b26074c2e772cade91460e6399dd795f7ceee2bb6e2cdad137e27d231d63c
        name: my-nodejs
        resources: {}
status: {}
